### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by BaDTimE-S4** [metallicafan212/UE2SelectionFixes#2]
Not really an issue, but if you could send me the parts of the original source code that you changed, I would appreciate a lot (or at least explain what is causing the problem, providing an insight, so I can fix also Swat4 Editor).

Btw, congratulations!

**Comment by metallicafan212** [comment]
I cannot share the source code, but I can explain how it works. Ask me in the OldUnreal discord 2k4 channels, and I'll happily explain. It's not an easy fix and it's not something you can just fix in the binary; these dlls are made with full source to the drivers, as it requires creating new shaders to use with selection.
